// <auto-generated />
using System;
using Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240507215509_DbTiendaRetail")]
    partial class DbTiendaRetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entitys.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnologia y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Eductivo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardineria y Bricola"
                        });
                });

            modelBuilder.Entity("Domain.Entitys.Parametry", b =>
                {
                    b.Property<int>("ParametriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParametriaId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ParametriaId");

                    b.ToTable("Parametry");

                    b.HasData(
                        new
                        {
                            ParametriaId = 1,
                            Codigo = "taxe_iva",
                            Value = 21m
                        });
                });

            modelBuilder.Entity("Domain.Entitys.Product", b =>
                {
                    b.Property<Guid>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductoId = new Guid("518aeebb-c952-4733-a160-261cd33538c8"),
                            CategoryId = 1,
                            Description = "Lavarropas con capacidad de 12 Kg, 14 programas de lavado, eficiencia energética A, centrifugado de 750 rpm, función antiarrugas, dispensador automático de detergente, puerta con visor de vidrio templado y panel de control electrónico.",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/bc553a4d53bb5eb5f9e44184047b212b.jpg.webp",
                            Name = "Lavarropas Carga Frontal Drean Next 6 Kg",
                            Price = 679999m
                        },
                        new
                        {
                            ProductoId = new Guid("39fa7e61-6349-454b-872f-b42ee362b3b2"),
                            CategoryId = 1,
                            Description = "Heladera con capacidad total de 311 litros, 224 litros de heladera y 87 litros de freezer. Sistema de frío No Frost, eficiencia energética A, 4 estrellas de freezer, función de congelamiento rápido, dispenser de agua y luz LED interior.",
                            Discount = 11,
                            ImageUrl = "https://images.fravega.com/f300/a55db6e62b330fc4768c2bfa9370a5b0.jpg.webp",
                            Name = "Heladera Cíclica GAFA HGF358AFB 282Lts Blanca",
                            Price = 629999m
                        },
                        new
                        {
                            ProductoId = new Guid("1824f116-da8a-4e6e-8801-bde12d3480c3"),
                            CategoryId = 1,
                            Description = "Aire acondicionado con capacidad de frío de 3000 frigorías y capacidad de calor de 3000 watts. Tecnología Inverter, eficiencia energética A, función de deshumidificación, timer programable, control remoto y modo Sleep.",
                            Discount = 5,
                            ImageUrl = "https://www.fravega.com/p/aire-acondicionado-split-frio-calor-surrey-3000f-3490w-553bfq1201e--20459/",
                            Name = "Aire Acondicionado Split Surrey Inverter Frio/Calor 3000 F",
                            Price = 1489999m
                        },
                        new
                        {
                            ProductoId = new Guid("66ad7a0c-73ad-4120-a620-271f7324f525"),
                            CategoryId = 1,
                            Description = "Lavadora de carga frontal con capacidad de lavado de 10.5 kg. Tecnología EcoBubble que activa el detergente con aire y agua antes de que comience el ciclo de lavado, garantizando una limpieza profunda incluso en agua fría. Eficiencia energética A+++, múltiples programas de lavado, pantalla LED táctil, y sistema de auto-limpieza.",
                            Discount = 4,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910743-MLA73490348656_122023-O.webp",
                            Name = "Lavarropa Samsung Ww10t504daw 10kg Blanco Con Ia Inverter",
                            Price = 2000999m
                        },
                        new
                        {
                            ProductoId = new Guid("b97801da-957f-4729-84be-7ed78f167f23"),
                            CategoryId = 2,
                            Description = "Televisor Smart TV LED LG de 50 pulgadas con resolución 4K UHD. Cuenta con tecnología LED para un brillo y contraste excepcionales, y su procesador inteligente te garantiza imágenes nítidas y colores vibrantes. Además, su plataforma Smart TV te permite acceder a tus aplicaciones favoritas de streaming con facilidad.",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/9f3103a4c80350aadc0f1f228cbab083.jpg.webp",
                            Name = "Televisor Smart TV LED 50\" 4K UHD LG 50UQ9300PTA",
                            Price = 573999m
                        },
                        new
                        {
                            ProductoId = new Guid("dabb3841-2e67-43e0-b741-6f8c3097a55b"),
                            CategoryId = 2,
                            Description = "El celular Samsung Galaxy S23 Ultra 5G es el teléfono inteligente definitivo para los amantes de la tecnología. Con una pantalla AMOLED de 6.8 pulgadas y un potente procesador Snapdragon 8 Gen 1, este teléfono te ofrece un rendimiento ultrarrápido y una experiencia visual inmersiva. Además, su sistema de cámara cuádruple trasera de 108 MP te permite capturar fotos y videos impresionantes.",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/68684fb77ad8b2609023cefea3c6c094.jpg.webp",
                            Name = "Celular Samsung Galaxy S23 Ultra 5G 256GB",
                            Price = 249999m
                        },
                        new
                        {
                            ProductoId = new Guid("323da16e-26cc-4afc-98fb-e8d695afabcf"),
                            CategoryId = 2,
                            Description = "Disfruta de tus juegos favoritos con el notebook gamer Lenovo Legion 5. Este potente equipo cuenta con un procesador AMD Ryzen 7 6800H, una placa de video NVIDIA GeForce RTX 3050 Ti y 16 GB de RAM, lo que te garantiza un rendimiento fluido y sin interrupciones. Además, su pantalla Full HD de 15.6 pulgadas con una tasa de refresco de 165 Hz te brinda imágenes nítidas y una experiencia de juego inmersiva.",
                            Discount = 10,
                            ImageUrl = "https://www.fravega.com.ar/wcsstore/fravega/images/catalog/2023/Febrero/02-02-2023/82JW007LAR-01.jpg",
                            Name = "Notebook Gamer Lenovo Legion 5 15ACH6H 82JW007LAR",
                            Price = 299999m
                        },
                        new
                        {
                            ProductoId = new Guid("c89adda0-13ec-46e2-a96a-26c15d5d0170"),
                            CategoryId = 2,
                            Description = "Disfruta de imágenes nítidas y colores vibrantes con el Smart TV LG 4K UHD 55' UP77. Con una pantalla de 55 pulgadas, resolución 4K UHD, y tecnología de mejora de imagen AI Picture, ofrece una experiencia visual envolvente. Además, cuenta con webOS, control por voz, y múltiples opciones de conectividad para acceder a tus contenidos favoritos.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_672706-MLU75135396807_032024-O.webp",
                            Name = "Smart TV LG 4K UHD 55' UP77",
                            Price = 799999m
                        },
                        new
                        {
                            ProductoId = new Guid("201bb12f-9780-40b9-86ae-48b61e5bb56b"),
                            CategoryId = 3,
                            Description = "Estas zapatillas deportivas con plataforma son perfectas para un look casual y cómodo. Su diseño moderno y trendy te hará destacar entre la multitud. La plataforma te dará un poco de altura extra y la suela acolchada te brindará comodidad durante todo el día.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_809755-MLA74807971075_022024-O.webp",
                            Name = "Zapatillas Fila deportivas con plataforma",
                            Price = 79999m
                        },
                        new
                        {
                            ProductoId = new Guid("38494165-f789-4506-964f-cee6debc6259"),
                            CategoryId = 3,
                            Description = "Este bolso de mano con diseño animal print es el accesorio perfecto para cualquier outfit. Su diseño elegante y sofisticado te hará sentir segura y glamorosa. El tamaño perfecto para llevar todo lo que necesitas.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_908309-MLA43823200371_102020-F.webp",
                            Name = "Bolso de mano con diseño animal print",
                            Price = 12999m
                        },
                        new
                        {
                            ProductoId = new Guid("01f3cd25-a66d-47a4-ae34-5f34283ed359"),
                            CategoryId = 3,
                            Description = "Este vestido midi con estampado floral es perfecto para cualquier ocasión. Su diseño elegante y femenino te hará sentir segura y hermosa. El tejido suave y fluido te mantendrá cómoda durante todo el día.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_827000-MLA73259012235_122023-F.webp",
                            Name = "Vestido midi con estampado floral",
                            Price = 19199m
                        },
                        new
                        {
                            ProductoId = new Guid("c3d89639-cd7a-4908-af1c-1c78fbd8d83f"),
                            CategoryId = 3,
                            Description = "Cafetera Espresso De'Longhi Dedica con bomba de presión de 15 bares. Diseño compacto y elegante. Opciones de preparación personalizadas. Disfruta de café de alta calidad en casa.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_924147-MLA32583951215_102019-O.webp",
                            Name = "Cafetera Espresso De'Longhi Dedica",
                            Price = 82999m
                        },
                        new
                        {
                            ProductoId = new Guid("eec38ecf-7ac1-4c88-8089-fe2099477533"),
                            CategoryId = 4,
                            Description = "Este juego de sábanas de algodón 100% te brindará una experiencia de sueño confortable y placentera. El algodón es un material suave y transpirable que te mantendrá fresco en verano y cálido en invierno.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_992437-MLU73437277182_122023-O.webp",
                            Name = "Juego de sábanas de algodón 100%",
                            Price = 40999m
                        },
                        new
                        {
                            ProductoId = new Guid("72191b2b-b4a3-485b-a1dd-00c4c46f4f3a"),
                            CategoryId = 4,
                            Description = "Este sofá de dos plazas con diseño moderno es perfecto para cualquier living. Su diseño elegante y minimalista le dará un toque de sofisticación a tu hogar. El tapizado de tela es suave y resistente.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_953815-MLA46281130948_062021-O.webp",
                            Name = "Sofá de dos plazas con diseño moderno",
                            Price = 1000000m
                        },
                        new
                        {
                            ProductoId = new Guid("6cda1640-ec45-48c9-964d-39e386b20448"),
                            CategoryId = 4,
                            Description = "Este juego de vajilla para 6 personas es perfecto para cualquier ocasión. Su diseño clásico y elegante le dará un toque de distinción a tu mesa. El material de porcelana es resistente y duradero.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_915185-MLA75190486128_032024-F.webp",
                            Name = "Juego de vajilla para 6 personas",
                            Price = 34879m
                        },
                        new
                        {
                            ProductoId = new Guid("2040d461-02f5-49c2-be7b-4eb438c642a3"),
                            CategoryId = 4,
                            Description = "Set de 3 cuadros decorativos modernos con diseños abstractos. Fabricados con materiales de alta calidad. Ideal para renovar tu espacio con estilo.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_891360-MLA50450337942_062022-O.webp",
                            Name = "Set de 3 Cuadros Decorativos Modernos",
                            Price = 8999m
                        },
                        new
                        {
                            ProductoId = new Guid("9ced7950-289d-4e8e-86e6-f733e5cbc6da"),
                            CategoryId = 5,
                            Description = "Esta crema hidratante facial con ácido hialurónico es perfecta para todo tipo de piel. El ácido hialurónico es un ingrediente que ayuda a retener la hidratación en la piel, lo que la hace lucir más joven y radiante.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_651558-MLA52220013087_102022-O.webp",
                            Name = "Crema hidratante facial con ácido hialurónico",
                            Price = 24631m
                        },
                        new
                        {
                            ProductoId = new Guid("3777f689-d2c4-423c-a895-182ed25f5667"),
                            CategoryId = 5,
                            Description = "Este cepillo de dientes eléctrico sónico te ayudará a tener una limpieza bucal más profunda y efectiva. Las cerdas sónicas vibran a alta velocidad para eliminar la placa y el sarro de forma eficaz.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_640938-MLA74353765176_022024-F.webp",
                            Name = "Cepillo de dientes eléctrico sónico",
                            Price = 27953m
                        },
                        new
                        {
                            ProductoId = new Guid("ff42a759-248f-4b2b-997e-ffd3cd2324c6"),
                            CategoryId = 5,
                            Description = "Este labial de larga duración te brindará un color intenso y duradero. Su fórmula especial es resistente al agua y a los besos.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_990774-MLU75051228244_032024-F.webp",
                            Name = "Maquillaje labial de larga duración",
                            Price = 45490m
                        },
                        new
                        {
                            ProductoId = new Guid("33d15e60-f860-4536-ae9b-4335e92ead82"),
                            CategoryId = 5,
                            Description = "Secador de pelo profesional con tecnología Ionic Ceramic para un secado rápido y sin frizz. Potente motor de 2200W con 3 ajustes de temperatura y 2 velocidades. Incluye boquilla concentradora y difusor para estilizar el cabello según tus preferencias. Consigue un cabello suave, brillante y saludable con este secador de pelo de calidad profesional.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_797457-MLA49192142777_022022-O.webp",
                            Name = "Secador de Pelo Profesional Ionic Ceramic",
                            Price = 59299m
                        },
                        new
                        {
                            ProductoId = new Guid("ce53c62d-e77f-43f6-bea4-2a5303f7b251"),
                            CategoryId = 6,
                            Description = "Esta pelota de fútbol es perfecta para jugar con amigos o en familia. Su diseño clásico y su material resistente te brindarán horas de diversión.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_814346-MLU72542363030_112023-O.webp",
                            Name = "Pelota de fútbol",
                            Price = 29890m
                        },
                        new
                        {
                            ProductoId = new Guid("9d0c45bb-ef9e-4669-95db-b2e773efff79"),
                            CategoryId = 6,
                            Description = "Esta bicicleta de montaña es perfecta para los amantes del ciclismo. Su diseño resistente y duradero te permitirá disfrutar de tus aventuras al aire libre.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_692292-MLA48659462745_122021-O.webp",
                            Name = "Bicicleta de montaña",
                            Price = 314689m
                        },
                        new
                        {
                            ProductoId = new Guid("c12587ce-e570-47bb-ad01-d5a98de7068a"),
                            CategoryId = 6,
                            Description = "Este juego de mesa es perfecto para pasar un rato divertido en familia. Su diseño atractivo y sus reglas sencillas te brindarán horas de entretenimiento.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_742516-MLA44728186422_012021-F.webp",
                            Name = "Juego de mesa para toda la familia",
                            Price = 19061m
                        },
                        new
                        {
                            ProductoId = new Guid("a5944141-8c1a-4a3a-ad7e-492c45f2fb33"),
                            CategoryId = 6,
                            Description = "Disfruta del agua con la tabla de paddle surf hinchable Aqua Marina Fusion. Fabricada con material de alta calidad, esta tabla ofrece estabilidad y durabilidad. Su diseño hinchable la hace fácil de transportar y almacenar. Equipada con una bomba de alta presión y una bolsa de transporte, es perfecta para explorar lagos, ríos y costas. ¡Sumérgete en la diversión con esta tabla de paddle surf!",
                            Discount = 8,
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0233/3953/2624/products/14-FUSION-01-2020-IMG_1737-2_1000x.jpg?v=1609160293",
                            Name = "Tabla de Paddle Surf Hinchable Aqua Marina Fusion",
                            Price = 189999m
                        },
                        new
                        {
                            ProductoId = new Guid("91407ebe-ced2-4d84-a30f-a23ce69df566"),
                            CategoryId = 7,
                            Description = "Estos bloques de construcción son perfectos para que los niños desarrollen su creatividad e imaginación. Con ellos podrán construir todo tipo de estructuras, desde casas y castillos hasta naves espaciales y robots.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_653633-MLU72122811116_102023-O.webp",
                            Name = "Bloques de construcción",
                            Price = 46509m
                        },
                        new
                        {
                            ProductoId = new Guid("f615213e-07f7-4043-b107-9e42dea29502"),
                            CategoryId = 7,
                            Description = "Esta muñeca es perfecta para que las niñas se diviertan y aprendan a cuidar de los demás. Viene con ropa y accesorios para que las niñas puedan crear todo tipo de historias.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_891562-MLU74194879919_012024-O.webp",
                            Name = "Muñeca",
                            Price = 27169m
                        },
                        new
                        {
                            ProductoId = new Guid("55fcc465-704e-4287-998c-bfded3a14d97"),
                            CategoryId = 7,
                            Description = "Este juego de mesa es perfecto para que los niños se diviertan en familia. Sus reglas sencillas y su diseño atractivo lo hacen ideal para niños de todas las edades.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_874287-MLU72637351761_112023-O.webp",
                            Name = "Juego de mesa para niños",
                            Price = 44399m
                        },
                        new
                        {
                            ProductoId = new Guid("5aa36dd5-1899-4eee-93b6-81c5c6726349"),
                            CategoryId = 7,
                            Description = "Construye una de las maravillas del mundo con el set LEGO Creator Expert Taj Mahal. Este impresionante set incluye más de 9500 piezas para recrear fielmente este icónico monumento. Con detalles intrincados y una escala impresionante, esta maqueta proporciona una experiencia de construcción desafiante y gratificante para aficionados y coleccionistas. ¡Embárcate en un viaje arquitectónico con este magnífico set de LEGO!",
                            Discount = 9,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_794783-MLA54926679565_042023-O.webp",
                            Name = "l",
                            Price = 339999m
                        },
                        new
                        {
                            ProductoId = new Guid("ea816fb4-eacd-42aa-9994-b2d6d10cf250"),
                            CategoryId = 8,
                            Description = "Estas manzanas frescas son de la mejor calidad y tienen un sabor delicioso. Son perfectas para comer como snack o para usar en recetas.",
                            Discount = 0,
                            ImageUrl = "https://img.freepik.com/foto-gratis/manzanas-rojas-frescas-suaves-jugosas-enteras-perfectas-escritorio-blanco_179666-271.jpg",
                            Name = "Manzanas frescas",
                            Price = 2999m
                        },
                        new
                        {
                            ProductoId = new Guid("73988485-0742-455d-8e52-df3d56cfebc0"),
                            CategoryId = 8,
                            Description = "Esta leche descremada es ideal para aquellos que buscan una opción más saludable. Es baja en calorías y grasa, pero aún así tiene un sabor delicioso.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_794418-MLU73783720994_012024-F.webp",
                            Name = "Leche descremada",
                            Price = 1790m
                        },
                        new
                        {
                            ProductoId = new Guid("0f838257-ea41-4b98-938f-380b8eeffb6a"),
                            CategoryId = 8,
                            Description = "Estas galletas de chocolate son perfectas para disfrutar con un café o un té. Son deliciosas y crujientes.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_770512-MLA52795200078_122022-O.webp",
                            Name = "Galletas de chocolate",
                            Price = 2849m
                        },
                        new
                        {
                            ProductoId = new Guid("33cfed73-dd37-4968-84d8-6286a466a3a6"),
                            CategoryId = 8,
                            Description = "Explora el mundo del vino con este kit de degustación que incluye una selección de vinos de diferentes variedades y regiones. Cada botella está cuidadosamente seleccionada para ofrecer una experiencia única de degustación. Descubre nuevos sabores, aromas y texturas mientras disfrutas de una velada especial con amigos o familiares.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_778460-MLA74696522802_022024-F.webp",
                            Name = "Kit de Degustación de Vinos",
                            Price = 4999m
                        },
                        new
                        {
                            ProductoId = new Guid("7d431943-3a01-4733-a5f8-b119b7ffaecc"),
                            CategoryId = 9,
                            Description = "Este libro de ficción es una novela apasionante que te atrapará desde el principio.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_790538-MLU73106969282_122023-O.webp",
                            Name = "Libro de ficción",
                            Price = 22900m
                        },
                        new
                        {
                            ProductoId = new Guid("226b352a-3a49-49ce-8994-4622926396be"),
                            CategoryId = 9,
                            Description = "Estos lápices de colores son ideales para que los niños exploren su creatividad.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_625215-MLU73129288734_122023-O.webp",
                            Name = "Lápices de colores",
                            Price = 19999m
                        },
                        new
                        {
                            ProductoId = new Guid("dbc63226-819b-4732-8919-8db8bfed915b"),
                            CategoryId = 9,
                            Description = "Este cuaderno de notas es perfecto para tomar apuntes en clase o en la oficina.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_969804-MLU72605081373_102023-O.webp",
                            Name = "Cuaderno de notas",
                            Price = 11990m
                        },
                        new
                        {
                            ProductoId = new Guid("4e059cff-8ac9-4421-baec-073b83627976"),
                            CategoryId = 9,
                            Description = "Descubre una variedad de deliciosas recetas de diferentes culturas y regiones del mundo con este libro de cocina. Desde platos tradicionales hasta opciones modernas, este libro te guiará a través de pasos sencillos para crear comidas increíbles en tu propia cocina. Con fotografías inspiradoras y consejos útiles, es perfecto para chefs aficionados y entusiastas de la cocina.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_622837-MLU74371917389_022024-O.webp",
                            Name = "Libro de Cocina: Recetas del Mundo",
                            Price = 1999m
                        },
                        new
                        {
                            ProductoId = new Guid("fe4312d7-8d3c-4f7f-ab01-8f05e99e603a"),
                            CategoryId = 10,
                            Description = "Estas tijeras de podar son ideales para cortar ramas y tallos de plantas.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_997006-MLU73673556155_122023-O.webp",
                            Name = "Tijeras de podar",
                            Price = 64368m
                        },
                        new
                        {
                            ProductoId = new Guid("5e2cee25-2243-4f90-ac2d-a9df74551741"),
                            CategoryId = 10,
                            Description = "Esta manguera de jardín es perfecta para regar tus plantas y flores.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_924765-MLU75436466640_042024-O.webp",
                            Name = "Manguera de jardín",
                            Price = 41582m
                        },
                        new
                        {
                            ProductoId = new Guid("2fb85e9f-8546-4d84-a9bc-23e4535fbb66"),
                            CategoryId = 10,
                            Description = "Este kit de herramientas básicas es perfecto para realizar pequeños trabajos de bricolaje en casa.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_649163-MLU75509398453_032024-O.webp",
                            Name = "Kit de herramientas básicas",
                            Price = 65499m
                        },
                        new
                        {
                            ProductoId = new Guid("e0df1b5a-fefa-4026-9f82-83c1bd2cf0f0"),
                            CategoryId = 10,
                            Description = "Haz que tu jardín florezca con este completo kit de herramientas de jardinería. Incluye una variedad de herramientas esenciales como palas, rastrillos, tijeras de podar y más, todo en un práctico estuche. Diseñadas para durar y facilitar el trabajo en el jardín, estas herramientas te ayudarán a mantener tu espacio verde hermoso y saludable durante todo el año.",
                            Discount = 9,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_845110-MLA43219745617_082020-O.webp",
                            Name = "Kit de Herramientas de Jardinería",
                            Price = 2299m
                        });
                });

            modelBuilder.Entity("Domain.Entitys.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entitys.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Product");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("Sale");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entitys.Product", b =>
                {
                    b.HasOne("Domain.Entitys.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entitys.SaleProduct", b =>
                {
                    b.HasOne("Domain.Entitys.Product", "Product")
                        .WithMany("SaleProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitys.Sale", "Sales")
                        .WithMany("SaleProducts")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Domain.Entitys.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entitys.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Domain.Entitys.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
