// <auto-generated />
using System;
using Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240702042102_DbTiendaRetail")]
    partial class DbTiendaRetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entitys.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("Domain.Entitys.Parametry", b =>
                {
                    b.Property<int>("ParametriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParametriaId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ParametriaId");

                    b.ToTable("Parametry");

                    b.HasData(
                        new
                        {
                            ParametriaId = 1,
                            Codigo = "taxe_iva",
                            Value = 21m
                        });
                });

            modelBuilder.Entity("Domain.Entitys.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("493f5e2a-9088-4f7e-8545-932a11a88236"),
                            CategoryId = 1,
                            Description = "Lavarropas con capacidad de 12 Kg, 14 programas de lavado, eficiencia energética A, centrifugado de 750 rpm, función antiarrugas, dispensador automático de detergente, puerta con visor de vidrio templado y panel de control electrónico.",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/bc553a4d53bb5eb5f9e44184047b212b.jpg.webp",
                            Name = "Lavarropas Carga Frontal Drean Next 6 Kg",
                            Price = 679999m
                        },
                        new
                        {
                            ProductId = new Guid("eb559725-26d8-416f-96f6-98b9e4885190"),
                            CategoryId = 1,
                            Description = "Heladera con capacidad total de 311 litros, 224 litros de heladera y 87 litros de freezer. Sistema de frío No Frost, eficiencia energética A, 4 estrellas de freezer, función de congelamiento rápido, dispenser de agua y luz LED interior.",
                            Discount = 11,
                            ImageUrl = "https://images.fravega.com/f300/a55db6e62b330fc4768c2bfa9370a5b0.jpg.webp",
                            Name = "Heladera Cíclica GAFA HGF358AFB 282Lts Blanca",
                            Price = 629999m
                        },
                        new
                        {
                            ProductId = new Guid("64ce7527-1633-4c1e-8d6e-5d31d50473ca"),
                            CategoryId = 1,
                            Description = "Aire acondicionado con capacidad de frío de 3000 frigorías y capacidad de calor de 3000 watts. Tecnología Inverter, eficiencia energética A, función de deshumidificación, timer programable, control remoto y modo Sleep.",
                            Discount = 5,
                            ImageUrl = "https://www.fravega.com/p/aire-acondicionado-split-frio-calor-surrey-3000f-3490w-553bfq1201e--20459/",
                            Name = "Aire Acondicionado Split Surrey Inverter Frio/Calor 3000 F",
                            Price = 1489999m
                        },
                        new
                        {
                            ProductId = new Guid("10499221-7549-4bc0-91b6-79ec56debf2f"),
                            CategoryId = 1,
                            Description = "Lavadora de carga frontal con capacidad de lavado de 10.5 kg. Tecnología EcoBubble que activa el detergente con aire y agua antes de que comience el ciclo de lavado, garantizando una limpieza profunda incluso en agua fría. Eficiencia energética A+++, múltiples programas de lavado, pantalla LED táctil, y sistema de auto-limpieza.",
                            Discount = 4,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_910743-MLA73490348656_122023-O.webp",
                            Name = "Lavarropa Samsung Ww10t504daw 10kg Blanco Con Ia Inverter",
                            Price = 2000999m
                        },
                        new
                        {
                            ProductId = new Guid("4472b7b0-2e85-4762-b04f-009370d61312"),
                            CategoryId = 1,
                            Description = "Microondas con capacidad de 25 litros, potencia de 800W, función de cocina rápida, pantalla LED y botones de control electrónicos.",
                            Discount = 2,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_798058-MLU74033812160_012024-O.webp",
                            Name = "Microondas Whirlpool MW 25 BA 25L",
                            Price = 449999m
                        },
                        new
                        {
                            ProductId = new Guid("c72f1c7f-4b62-4656-9a31-9f656c403c6a"),
                            CategoryId = 1,
                            Description = "Lavarropas con capacidad de 12 kg, tecnología Inverter, eficiencia energética A++, 14 programas de lavado, función de vapor para eliminar arrugas, y pantalla LED táctil.",
                            Discount = 3,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_742423-MLA51835012835_102022-O.webp",
                            Name = "Lavarropas LG F-1402H5B 12Kg Inverter",
                            Price = 899999m
                        },
                        new
                        {
                            ProductId = new Guid("5c3f922c-5d99-4f02-9593-d9cc5778f459"),
                            CategoryId = 1,
                            Description = "Heladera con capacidad total de 505 litros, 342 litros de heladera y 163 litros de freezer. Sistema de frío No Frost, eficiencia energética A++, 4 estrellas de freezer, función de congelamiento rápido, y dispenser de agua y hielo.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_972873-MLA50008739804_052022-O.webp",
                            Name = "Heladera Side by Side Samsung RS50N3513SL/AA 505Lts",
                            Price = 2499999m
                        },
                        new
                        {
                            ProductId = new Guid("5823d761-e70b-400f-b41e-ac683c0dc7ab"),
                            CategoryId = 1,
                            Description = "Aire acondicionado con capacidad de frío de 18000 frigorías y capacidad de calor de 18000 watts. Tecnología Inverter, eficiencia energética A++, función de deshumidificación, timer programable, control remoto y modo Sleep.",
                            Discount = 6,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_629906-MLA74780228753_022024-O.webp",
                            Name = "Aire Acondicionado Split LG F-Q186KXA 18000 F",
                            Price = 1999999m
                        },
                        new
                        {
                            ProductId = new Guid("8104ba35-81a6-4304-9426-8547eb97ac92"),
                            CategoryId = 1,
                            Description = "Lavarropas con capacidad de 8 kg, tecnología Inverter, eficiencia energética A++, 14 programas de lavado, función de vapor para eliminar arrugas, y pantalla LED táctil.",
                            Discount = 1,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_816984-MLA53496425042_012023-O.webp",
                            Name = "Lavarropas Drean Next 8 Kg Inverter",
                            Price = 749999m
                        },
                        new
                        {
                            ProductId = new Guid("747afc75-f14e-4edf-b1e9-e8dfd4eab984"),
                            CategoryId = 1,
                            Description = "Heladera con capacidad total de 311 litros, 224 litros de heladera y 87 litros de freezer. Sistema de frío No Frost, eficiencia energética A, 4 estrellas de freezer, función de congelamiento rápido, dispenser de agua y luz LED interior.",
                            Discount = 12,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_986989-MLU74218962327_012024-O.webp",
                            Name = "Heladera Cíclica GAFA HGF358AFB 282Lts Inoxidable",
                            Price = 699999m
                        },
                        new
                        {
                            ProductId = new Guid("8e7c0ac3-1330-4a28-81fd-aa02589db270"),
                            CategoryId = 1,
                            Description = "Microondas con capacidad de 27 litros, potencia de 1000W, función de cocina rápida, pantalla LED y botones de control electrónicos.",
                            Discount = 2,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_858971-MLA74978511181_032024-O.webp",
                            Name = "Microondas Panasonic NN-ST665B 27L",
                            Price = 549999m
                        },
                        new
                        {
                            ProductId = new Guid("12a4d047-f748-4425-bfb0-c1829ddc7320"),
                            CategoryId = 2,
                            Description = "Televisor Smart TV LED LG de 50 pulgadas con resolución 4K UHD. Cuenta con tecnología LED para un brillo y contraste excepcionales, y su procesador inteligente te garantiza imágenes nítidas y colores vibrantes. Además, su plataforma Smart TV te permite acceder a tus aplicaciones favoritas de streaming con facilidad.",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/9f3103a4c80350aadc0f1f228cbab083.jpg.webp",
                            Name = "Televisor Smart TV LED 50\" 4K UHD LG 50UQ9300PTA",
                            Price = 573999m
                        },
                        new
                        {
                            ProductId = new Guid("8ebd765b-e14f-4ed9-9da6-46987bb34c7f"),
                            CategoryId = 2,
                            Description = "El celular Samsung Galaxy S23 Ultra 5G es el teléfono inteligente definitivo para los amantes de la tecnología. Con una pantalla AMOLED de 6.8 pulgadas y un potente procesador Snapdragon 8 Gen 1, este teléfono te ofrece un rendimiento ultrarrápido y una experiencia visual inmersiva. Además, su sistema de cámara cuádruple trasera de 108 MP te permite capturar fotos y videos impresionantes.",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/68684fb77ad8b2609023cefea3c6c094.jpg.webp",
                            Name = "Celular Samsung Galaxy S23 Ultra 5G 256GB",
                            Price = 249999m
                        },
                        new
                        {
                            ProductId = new Guid("c340ebcc-ee75-43e7-9b4f-faa9b9c0caa7"),
                            CategoryId = 2,
                            Description = "Disfruta de tus juegos favoritos con el notebook gamer Lenovo Legion 5. Este potente equipo cuenta con un procesador AMD Ryzen 7 6800H, una placa de video NVIDIA GeForce RTX 3050 Ti y 16 GB de RAM, lo que te garantiza un rendimiento fluido y sin interrupciones. Además, su pantalla Full HD de 15.6 pulgadas con una tasa de refresco de 165 Hz te brinda imágenes nítidas y una experiencia de juego inmersiva.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_871625-MLA75823629201_042024-O.webp",
                            Name = "Notebook Gamer Lenovo Legion 5 15ACH6H 82JW007LAR",
                            Price = 299999m
                        },
                        new
                        {
                            ProductId = new Guid("839db146-dc5c-4d8f-a935-0520dc75fa52"),
                            CategoryId = 2,
                            Description = "Disfruta de imágenes nítidas y colores vibrantes con el Smart TV LG 4K UHD 55' UP77. Con una pantalla de 55 pulgadas, resolución 4K UHD, y tecnología de mejora de imagen AI Picture, ofrece una experiencia visual envolvente. Además, cuenta con webOS, control por voz, y múltiples opciones de conectividad para acceder a tus contenidos favoritos.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_672706-MLU75135396807_032024-O.webp",
                            Name = "Smart TV LG 4K UHD 55' UP77",
                            Price = 799999m
                        },
                        new
                        {
                            ProductId = new Guid("a3824796-bfc5-4bb6-8880-3190bd6dc456"),
                            CategoryId = 2,
                            Description = "La nueva iPad Pro de 12.9 pulgadas de Apple ofrece una potencia sin igual gracias a su chip M1. Con 128GB de almacenamiento y una pantalla Liquid Retina XDR, es perfecta para tareas creativas y de productividad. Además, cuenta con un sistema de cámaras avanzadas y compatibilidad con el Apple Pencil y el Magic Keyboard.",
                            Discount = 3,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_814559-MLA53970921150_022023-O.webp",
                            Name = "Tablet Apple iPad Pro 12.9\" 128GB Wi-Fi",
                            Price = 1029999m
                        },
                        new
                        {
                            ProductId = new Guid("481ae260-2d71-48e3-9ff6-a19c2e18a066"),
                            CategoryId = 2,
                            Description = "El Apple Watch Series 7 cuenta con una pantalla más grande y avanzada, resistencia al polvo y al agua, y un cargado rápido. Además, incluye funcionalidades de salud y fitness como monitoreo de oxígeno en sangre, ECG y una amplia variedad de aplicaciones deportivas.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_858093-MLA48096508611_112021-O.webp",
                            Name = "Smartwatch Apple Watch Series 7 GPS 45mm",
                            Price = 529999m
                        },
                        new
                        {
                            ProductId = new Guid("de0f12b2-bc20-46a8-9616-8a352341532b"),
                            CategoryId = 2,
                            Description = "Los auriculares Sony WH-1000XM4 ofrecen una cancelación de ruido líder en la industria, un sonido excepcional y comodidad durante todo el día. Con una batería de larga duración y características inteligentes como el control táctil y el Speak-to-Chat, son ideales para disfrutar de tu música sin interrupciones.",
                            Discount = 12,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_918604-MLA44483909501_012021-O.webp",
                            Name = "Auriculares Inalámbricos Sony WH-1000XM4",
                            Price = 149999m
                        },
                        new
                        {
                            ProductId = new Guid("64d627df-249f-4521-822b-5168b01915e2"),
                            CategoryId = 2,
                            Description = "La consola PlayStation 5 de Sony ofrece una experiencia de juego de próxima generación con gráficos impresionantes, tiempos de carga ultrarrápidos y una nueva generación de juegos exclusivos. Su controlador DualSense proporciona una inmersión sin precedentes gracias a su respuesta háptica y gatillos adaptativos.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_802856-MLU76753493373_052024-O.webp",
                            Name = "Consola PlayStation 5",
                            Price = 1199999m
                        },
                        new
                        {
                            ProductId = new Guid("91c609c8-cfff-44e8-9c71-50f649ebf8de"),
                            CategoryId = 2,
                            Description = "El JBL Charge 5 es un parlante Bluetooth portátil que ofrece un sonido potente y claro. Con una batería de hasta 20 horas de duración, resistencia al agua y polvo (IP67) y la capacidad de cargar tus dispositivos móviles, es perfecto para llevar tu música a cualquier lugar.",
                            Discount = 15,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_778458-MLU72636564641_112023-O.webp",
                            Name = "Parlante Bluetooth JBL Charge 5",
                            Price = 69999m
                        },
                        new
                        {
                            ProductId = new Guid("845dcfaf-85a2-4a1c-b56a-e4427c4702c3"),
                            CategoryId = 2,
                            Description = "El monitor curvo de Samsung de 27 pulgadas te ofrece una experiencia inmersiva con su pantalla Full HD y una curvatura 1800R. Con tecnología AMD FreeSync y una frecuencia de actualización de 75 Hz, es ideal para juegos y entretenimiento.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_904906-MLU69761863493_062023-O.webp",
                            Name = "Monitor Samsung Curvo 27\" Full HD LC27R500FHNXZA",
                            Price = 109999m
                        },
                        new
                        {
                            ProductId = new Guid("ae71899c-ea1f-4e2a-8a1c-5fd1d5ad969b"),
                            CategoryId = 2,
                            Description = "La cámara Canon EOS Rebel T7 es perfecta para fotógrafos principiantes. Cuenta con un sensor CMOS de 24.1 MP, pantalla LCD de 3 pulgadas y conectividad Wi-Fi para compartir tus fotos al instante. Además, incluye una lente 18-55mm.",
                            Discount = 5,
                            ImageUrl = "",
                            Name = "Cámara Canon EOS Rebel T7",
                            Price = 189999m
                        },
                        new
                        {
                            ProductId = new Guid("9f709330-d2ea-4e32-aaf0-a36d6dec1ede"),
                            CategoryId = 2,
                            Description = "El MacBook Pro de 14 pulgadas con chip M1 Pro de Apple ofrece un rendimiento y eficiencia excepcionales. Con una pantalla Liquid Retina XDR, hasta 32GB de RAM y 1TB de almacenamiento SSD, es ideal para profesionales creativos.",
                            Discount = 3,
                            ImageUrl = "",
                            Name = "Laptop Apple MacBook Pro 14\" M1 Pro",
                            Price = 2399999m
                        },
                        new
                        {
                            ProductId = new Guid("c5c4b492-0cc1-43d2-8640-fc0353bd6dc1"),
                            CategoryId = 2,
                            Description = "El DJI Mavic Air 2 es un drone avanzado con una cámara 4K de 48MP, tiempo de vuelo de hasta 34 minutos y múltiples modos de vuelo inteligentes. Perfecto para capturar fotos y videos aéreos de alta calidad.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_727004-MLA75232255242_032024-O.webp",
                            Name = "Drone DJI Mavic Air 2",
                            Price = 699999m
                        },
                        new
                        {
                            ProductId = new Guid("5bd07182-4ebd-474f-9409-ae4443a557e8"),
                            CategoryId = 2,
                            Description = "La Bose Smart Soundbar 700 ofrece un sonido inmersivo y conectividad inteligente con Alexa y Google Assistant integrados. Su diseño elegante y su rendimiento acústico superior mejoran cualquier sistema de entretenimiento en el hogar.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_843862-MLA42478366506_072020-O.webp",
                            Name = "Barra de Sonido Bose Smart Soundbar 700",
                            Price = 399999m
                        },
                        new
                        {
                            ProductId = new Guid("d6621840-55e2-4ff8-b43d-6b76f90c792a"),
                            CategoryId = 2,
                            Description = "La HP OfficeJet Pro 9015e es una impresora multifuncional ideal para oficinas pequeñas y medianas. Ofrece impresión a doble cara, escaneo, copia y fax con alta velocidad y calidad profesional.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_768300-MLA41233060022_032020-O.webp",
                            Name = "Impresora Multifuncional HP OfficeJet Pro 9015e",
                            Price = 229999m
                        },
                        new
                        {
                            ProductId = new Guid("da584d40-8c9d-41e1-8b8c-20dab49f8a73"),
                            CategoryId = 2,
                            Description = "El router ASUS RT-AX86U es ideal para juegos y transmisión en 4K. Ofrece tecnología WiFi 6 con velocidades de hasta 5700 Mbps, puerto gaming de 2.5 Gbps y seguridad AiProtection Pro.",
                            Discount = 12,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_760437-MLU76150445423_052024-O.webp",
                            Name = "Router WiFi 6 ASUS RT-AX86U",
                            Price = 199999m
                        },
                        new
                        {
                            ProductId = new Guid("f491475c-666f-4efc-8d6e-c5e4c2f63221"),
                            CategoryId = 2,
                            Description = "El proyector Epson Home Cinema 2150 ofrece una experiencia de cine en casa con resolución Full HD 1080p, 2500 lúmenes de brillo y conectividad inalámbrica. Perfecto para ver películas y jugar videojuegos en gran pantalla.",
                            Discount = 6,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_650108-MLA74903080735_032024-O.webp",
                            Name = "Proyector Epson Home Cinema 2150",
                            Price = 299999m
                        },
                        new
                        {
                            ProductId = new Guid("5c313c60-4776-4264-8893-f3aa6bc6f55d"),
                            CategoryId = 2,
                            Description = "El Amazon Echo Dot de 4ta generación con reloj ofrece control por voz con Alexa, sonido mejorado y un diseño elegante. Ideal para gestionar dispositivos inteligentes, reproducir música y obtener información instantánea.",
                            Discount = 15,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_907304-MLA76219497482_052024-O.webp",
                            Name = "Bocina Inteligente Amazon Echo Dot 4ta Generación",
                            Price = 49999m
                        },
                        new
                        {
                            ProductId = new Guid("dd43bca7-9cc0-4566-a34e-e5f6a4a662e3"),
                            CategoryId = 2,
                            Description = "La Ring Stick Up Cam Battery es una cámara de seguridad versátil para interiores y exteriores. Ofrece video HD 1080p, detección de movimiento, visión nocturna y comunicación bidireccional. Funciona con batería recargable o alimentación solar.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_968604-MLA73899541113_012024-O.webp",
                            Name = "Cámara de Seguridad Ring Stick Up Cam Battery",
                            Price = 89999m
                        },
                        new
                        {
                            ProductId = new Guid("5a3a3106-90d8-41d2-b800-65f07f98c253"),
                            CategoryId = 2,
                            Description = "Los Bose QuietComfort Earbuds ofrecen cancelación de ruido avanzada, sonido de alta calidad y un ajuste cómodo y seguro. Son ideales para disfrutar de tu música sin interrupciones, con una batería de hasta 6 horas de duración.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_609529-MLU74226371875_012024-O.webp",
                            Name = "Audífonos Bluetooth Bose QuietComfort Earbuds",
                            Price = 199999m
                        },
                        new
                        {
                            ProductId = new Guid("bcfb8ca3-be5f-4f2e-9a3f-3b72ee397ae9"),
                            CategoryId = 3,
                            Description = "Estas zapatillas deportivas con plataforma son perfectas para un look casual y cómodo. Su diseño moderno y trendy te hará destacar entre la multitud. La plataforma te dará un poco de altura extra y la suela acolchada te brindará comodidad durante todo el día.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_809755-MLA74807971075_022024-O.webp",
                            Name = "Zapatillas Fila deportivas con plataforma",
                            Price = 79999m
                        },
                        new
                        {
                            ProductId = new Guid("d373d1fd-f8e4-484c-834a-fe7486a24bb8"),
                            CategoryId = 3,
                            Description = "Este bolso de mano con diseño animal print es el accesorio perfecto para cualquier outfit. Su diseño elegante y sofisticado te hará sentir segura y glamorosa. El tamaño perfecto para llevar todo lo que necesitas.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_908309-MLA43823200371_102020-F.webp",
                            Name = "Bolso de mano con diseño animal print",
                            Price = 12999m
                        },
                        new
                        {
                            ProductId = new Guid("1b38086c-c077-4f91-896c-88329591644a"),
                            CategoryId = 3,
                            Description = "Este vestido midi con estampado floral es perfecto para cualquier ocasión. Su diseño elegante y femenino te hará sentir segura y hermosa. El tejido suave y fluido te mantendrá cómoda durante todo el día.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_827000-MLA73259012235_122023-F.webp",
                            Name = "Vestido midi con estampado floral",
                            Price = 19199m
                        },
                        new
                        {
                            ProductId = new Guid("dc847166-4337-403a-879d-6515c71158dc"),
                            CategoryId = 3,
                            Description = "Cafetera Espresso De'Longhi Dedica con bomba de presión de 15 bares. Diseño compacto y elegante. Opciones de preparación personalizadas. Disfruta de café de alta calidad en casa.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_924147-MLA32583951215_102019-O.webp",
                            Name = "Cafetera Espresso De'Longhi Dedica",
                            Price = 82999m
                        },
                        new
                        {
                            ProductId = new Guid("4b763a5a-cea1-4e3f-895b-919308958912"),
                            CategoryId = 3,
                            Description = "Las gafas de sol Ray-Ban Aviator son un clásico atemporal. Con su diseño elegante y lentes polarizados, ofrecen protección UV y estilo. Perfectas para cualquier ocasión.",
                            Discount = 20,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_876333-MLA74134571216_012024-O.webp",
                            Name = "Gafas de sol Ray-Ban Aviator",
                            Price = 19999m
                        },
                        new
                        {
                            ProductId = new Guid("f7c6677b-4922-449e-9cdc-af18270a575a"),
                            CategoryId = 3,
                            Description = "El Apple Watch Series 6 es un accesorio moderno y funcional. Con monitoreo de salud, GPS, y múltiples aplicaciones, es perfecto para mantenerte conectado y saludable.",
                            Discount = 15,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_792553-MLU73159525351_112023-O.webp",
                            Name = "Reloj inteligente Apple Watch Series 6",
                            Price = 499999m
                        },
                        new
                        {
                            ProductId = new Guid("d1f56722-2c05-44ef-9afb-ae928a026b8f"),
                            CategoryId = 3,
                            Description = "La mochila Jansport clásica es ideal para la escuela o el trabajo. Con amplio espacio de almacenamiento y diseño resistente, ofrece comodidad y durabilidad.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_967659-MLU70516232392_072023-O.webp",
                            Name = "Mochila Jansport clásica",
                            Price = 59999m
                        },
                        new
                        {
                            ProductId = new Guid("f552a825-cac9-435e-a10f-2c0ef24c5892"),
                            CategoryId = 3,
                            Description = "La cartera de cuero Michael Kors es un accesorio elegante y práctico. Con múltiples compartimentos y un diseño sofisticado, es perfecta para llevar tus esenciales con estilo.",
                            Discount = 12,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_990693-MLA74704426792_022024-O.webp",
                            Name = "Cartera de cuero Michael Kors",
                            Price = 159999m
                        },
                        new
                        {
                            ProductId = new Guid("b0cb9f88-e8ad-4900-a6d2-099328698493"),
                            CategoryId = 3,
                            Description = "El sombrero Fedora de lana es un accesorio clásico y elegante. Perfecto para añadir un toque de estilo a cualquier atuendo, este sombrero es ideal para el otoño e invierno.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_671496-MLA45427114933_042021-O.webp",
                            Name = "Sombrero Fedora de lana",
                            Price = 29999m
                        },
                        new
                        {
                            ProductId = new Guid("d489cb8d-6e04-4456-baba-a1fd77bb2a0b"),
                            CategoryId = 3,
                            Description = "La chaqueta de cuero negra es un básico de moda imprescindible. Con su diseño atemporal y ajuste perfecto, es ideal para cualquier ocasión y combina con todo.",
                            Discount = 7,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_829598-MLA75171128806_032024-O.webp",
                            Name = "Chaqueta de cuero negra",
                            Price = 249999m
                        },
                        new
                        {
                            ProductId = new Guid("c96aa170-9bed-44a6-8938-35edad3e8120"),
                            CategoryId = 3,
                            Description = "Los pantalones de mezclilla Levi's 501 son un clásico que nunca pasa de moda. Con su corte recto y ajuste cómodo, son ideales para un look casual y versátil.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_925069-MLA49693821162_042022-O.webp",
                            Name = "Pantalones de mezclilla Levi's 501",
                            Price = 99999m
                        },
                        new
                        {
                            ProductId = new Guid("81d92448-b7c6-4f4f-bf93-ef32578e8f95"),
                            CategoryId = 3,
                            Description = "Esta blusa de seda con lazo es perfecta para un look elegante y femenino. Su diseño delicado y tejido suave te harán sentir cómoda y chic en cualquier ocasión.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_668789-MLA73659925632_012024-O.webp",
                            Name = "Blusa de seda con lazo",
                            Price = 74999m
                        },
                        new
                        {
                            ProductId = new Guid("5152eaf7-2c7e-44dc-a547-08f3c0a768bc"),
                            CategoryId = 3,
                            Description = "El cinturón de cuero Calvin Klein es un accesorio sofisticado y versátil. Con su diseño minimalista y elegante, es perfecto para completar cualquier atuendo.",
                            Discount = 20,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_913222-MLA77275857767_062024-O.webp",
                            Name = "Cinturón de cuero Calvin Klein",
                            Price = 34999m
                        },
                        new
                        {
                            ProductId = new Guid("383ddb14-0b94-4aa2-b862-abbe3a9266e9"),
                            CategoryId = 3,
                            Description = "Las zapatillas deportivas Nike Air Max combinan estilo y comodidad. Con su diseño icónico y tecnología de amortiguación, son perfectas para el uso diario y actividades deportivas.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_912442-MLA77092906427_062024-O.webp",
                            Name = "Zapatillas deportivas Nike Air Max",
                            Price = 129999m
                        },
                        new
                        {
                            ProductId = new Guid("8f25b002-0cde-4971-aa82-7a9816db12dd"),
                            CategoryId = 3,
                            Description = "La bufanda de lana merino es un accesorio esencial para el invierno. Suave y cálida, es perfecta para mantenerte abrigado con estilo durante los días fríos.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_744846-MLA76662301416_062024-O.webp",
                            Name = "Bufanda de lana merino",
                            Price = 19999m
                        },
                        new
                        {
                            ProductId = new Guid("de2d73dd-e5d4-428c-9633-a5140aa1dfb8"),
                            CategoryId = 3,
                            Description = "El bolso tote de tela es práctico y estiloso. Con amplio espacio de almacenamiento y un diseño moderno, es perfecto para llevar tus esenciales diarios.",
                            Discount = 15,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_949148-MLU75692429655_042024-O.webp",
                            Name = "Bolso tote de tela",
                            Price = 44999m
                        },
                        new
                        {
                            ProductId = new Guid("fc129924-d674-48d2-844b-f77b3fc92cd2"),
                            CategoryId = 3,
                            Description = "Esta falda plisada midi es elegante y versátil. Con su diseño femenino y tejido ligero, es perfecta para cualquier ocasión, desde el trabajo hasta eventos especiales.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_713957-MLA70114688153_062023-O.webp",
                            Name = "Falda plisada midi",
                            Price = 59999m
                        },
                        new
                        {
                            ProductId = new Guid("cec7d134-208a-4442-afa4-69e2c09fe4da"),
                            CategoryId = 3,
                            Description = "Los botines de cuero marrón son un calzado clásico y atemporal. Con su diseño robusto y elegante, son perfectos para el uso diario y combinan con cualquier atuendo.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_777105-MLA70924305746_082023-O.webp",
                            Name = "Botines de cuero marrón",
                            Price = 149999m
                        },
                        new
                        {
                            ProductId = new Guid("4e0cccb5-7f69-430d-9734-5898c59d77a2"),
                            CategoryId = 3,
                            Description = "El gorro de lana tejido es un accesorio esencial para el invierno. Suave y cálido, es perfecto para mantener tu cabeza abrigada y añadir un toque de estilo a tu look.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_766012-MLA54959307419_042023-O.webp",
                            Name = "Gorro de lana tejido",
                            Price = 9999m
                        },
                        new
                        {
                            ProductId = new Guid("be588d92-9377-4e07-8178-295e804e2149"),
                            CategoryId = 4,
                            Description = "Este juego de sábanas de algodón 100% te brindará una experiencia de sueño confortable y placentera. El algodón es un material suave y transpirable que te mantendrá fresco en verano y cálido en invierno.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_992437-MLU73437277182_122023-O.webp",
                            Name = "Juego de sábanas de algodón 100%",
                            Price = 40999m
                        },
                        new
                        {
                            ProductId = new Guid("7531af6d-bda5-493e-8d1f-b441cec55349"),
                            CategoryId = 4,
                            Description = "Este sofá de dos plazas con diseño moderno es perfecto para cualquier living. Su diseño elegante y minimalista le dará un toque de sofisticación a tu hogar. El tapizado de tela es suave y resistente.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_953815-MLA46281130948_062021-O.webp",
                            Name = "Sofá de dos plazas con diseño moderno",
                            Price = 1000000m
                        },
                        new
                        {
                            ProductId = new Guid("e98ac605-9a63-4a1f-aa65-f45f61061076"),
                            CategoryId = 4,
                            Description = "Este juego de vajilla para 6 personas es perfecto para cualquier ocasión. Su diseño clásico y elegante le dará un toque de distinción a tu mesa. El material de porcelana es resistente y duradero.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_915185-MLA75190486128_032024-F.webp",
                            Name = "Juego de vajilla para 6 personas",
                            Price = 34879m
                        },
                        new
                        {
                            ProductId = new Guid("da1c918e-0d4c-41be-a219-dbf1d4e25c45"),
                            CategoryId = 4,
                            Description = "Set de 3 cuadros decorativos modernos con diseños abstractos. Fabricados con materiales de alta calidad. Ideal para renovar tu espacio con estilo.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_891360-MLA50450337942_062022-O.webp",
                            Name = "Set de 3 Cuadros Decorativos Modernos",
                            Price = 8999m
                        },
                        new
                        {
                            ProductId = new Guid("65654ba7-4a3d-4dd6-99b8-b584a864b9a8"),
                            CategoryId = 4,
                            Description = "Esta alfombra de área grande es perfecta para darle un toque de calidez y estilo a tu hogar. Su diseño moderno y colores vibrantes complementarán cualquier decoración.",
                            Discount = 3,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_678277-MLA50585725957_072022-O.webp",
                            Name = "Alfombra de área grande",
                            Price = 59999m
                        },
                        new
                        {
                            ProductId = new Guid("c2ac30da-940a-4444-8b96-9192fa57b916"),
                            CategoryId = 4,
                            Description = "Esta lámpara de mesa de diseño es ideal para iluminar tu espacio con estilo. Su base elegante y pantalla de tela proporcionan una luz suave y agradable.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_747581-MLA73179961416_122023-O.webp",
                            Name = "Lámpara de mesa de diseño",
                            Price = 24999m
                        },
                        new
                        {
                            ProductId = new Guid("edfc8451-3709-4cfd-adb5-94dc06a62cdb"),
                            CategoryId = 4,
                            Description = "Las cortinas blackout de lino son perfectas para mantener la privacidad y bloquear la luz no deseada. Su tejido de alta calidad y diseño elegante mejorarán cualquier habitación.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_888846-MLA69964681489_062023-O.webp",
                            Name = "Cortinas blackout de lino",
                            Price = 32999m
                        },
                        new
                        {
                            ProductId = new Guid("8ccf2b77-a963-4f6d-b062-b24462cf386e"),
                            CategoryId = 4,
                            Description = "Esta estantería modular de madera es una solución de almacenamiento versátil y estilosa. Su diseño modular te permite personalizarla según tus necesidades.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_683332-MLU74725847452_032024-O.webp",
                            Name = "Estantería modular de madera",
                            Price = 45999m
                        },
                        new
                        {
                            ProductId = new Guid("0689d15c-35d1-4833-923b-4358877a97d0"),
                            CategoryId = 4,
                            Description = "Este juego de toallas de algodón egipcio es lujoso y absorbente. Perfecto para añadir un toque de elegancia a tu baño. El set incluye toallas de baño, de mano y toallas faciales.",
                            Discount = 12,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_935868-MLA76111646337_042024-O.webp",
                            Name = "Juego de toallas de algodón egipcio",
                            Price = 29999m
                        },
                        new
                        {
                            ProductId = new Guid("f1586e1d-7d7b-4de5-a8fa-49db28a84019"),
                            CategoryId = 4,
                            Description = "La planta artificial decorativa es perfecta para agregar un toque de verde a tu hogar sin necesidad de mantenimiento. Su diseño realista complementará cualquier decoración.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_611532-MLA72597798496_112023-O.webp",
                            Name = "Planta artificial decorativa",
                            Price = 15999m
                        },
                        new
                        {
                            ProductId = new Guid("f298d0b0-3583-4931-b14f-3b6e407f5fd0"),
                            CategoryId = 4,
                            Description = "El espejo de pared grande es un accesorio esencial para cualquier hogar. Su diseño elegante y marco robusto lo convierten en una pieza decorativa y funcional.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_983208-MLU75985619618_052024-O.webp",
                            Name = "Espejo de pared grande",
                            Price = 78999m
                        },
                        new
                        {
                            ProductId = new Guid("e58fb3a3-92c6-42b3-990a-b286dcd9cea3"),
                            CategoryId = 4,
                            Description = "Esta mesa de centro de madera y metal combina estilo industrial y funcionalidad. Es perfecta para complementar la decoración de tu sala de estar.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_867489-MLA74928886215_032024-O.webp",
                            Name = "Mesa de centro de madera y metal",
                            Price = 89999m
                        },
                        new
                        {
                            ProductId = new Guid("b4508792-22a1-4521-ae23-63fa4580c86c"),
                            CategoryId = 4,
                            Description = "La colcha de cama King size es ideal para agregar un toque de lujo a tu dormitorio. Su diseño elegante y material suave te proporcionarán confort y estilo.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_934128-MLA48538774826_122021-O.webp",
                            Name = "Colcha de cama King size",
                            Price = 54999m
                        },
                        new
                        {
                            ProductId = new Guid("b96a6657-abe6-4724-bada-3227726461e8"),
                            CategoryId = 4,
                            Description = "Este juego de candelabros de metal es perfecto para crear una atmósfera acogedora en tu hogar. Su diseño elegante y acabado en oro añaden un toque de sofisticación.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_866208-MLA74951585635_032024-O.webp",
                            Name = "Juego de candelabros de metal",
                            Price = 19999m
                        },
                        new
                        {
                            ProductId = new Guid("0e64fb18-bd4c-4e9d-a79a-929c2807c31b"),
                            CategoryId = 5,
                            Description = "Esta crema hidratante facial con ácido hialurónico es perfecta para todo tipo de piel. El ácido hialurónico es un ingrediente que ayuda a retener la hidratación en la piel, lo que la hace lucir más joven y radiante.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_651558-MLA52220013087_102022-O.webp",
                            Name = "Crema hidratante facial con ácido hialurónico",
                            Price = 24631m
                        },
                        new
                        {
                            ProductId = new Guid("444ef5da-84e9-447d-b96f-682fef2f44cc"),
                            CategoryId = 5,
                            Description = "Este cepillo de dientes eléctrico sónico te ayudará a tener una limpieza bucal más profunda y efectiva. Las cerdas sónicas vibran a alta velocidad para eliminar la placa y el sarro de forma eficaz.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_640938-MLA74353765176_022024-F.webp",
                            Name = "Cepillo de dientes eléctrico sónico",
                            Price = 27953m
                        },
                        new
                        {
                            ProductId = new Guid("5b771f0d-b062-4264-ad4d-334d91778d00"),
                            CategoryId = 5,
                            Description = "Este labial de larga duración te brindará un color intenso y duradero. Su fórmula especial es resistente al agua y a los besos.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_990774-MLU75051228244_032024-F.webp",
                            Name = "Maquillaje labial de larga duración",
                            Price = 45490m
                        },
                        new
                        {
                            ProductId = new Guid("6aca5803-849a-4413-9812-4705ccae4149"),
                            CategoryId = 5,
                            Description = "Secador de pelo profesional con tecnología Ionic Ceramic para un secado rápido y sin frizz. Potente motor de 2200W con 3 ajustes de temperatura y 2 velocidades. Incluye boquilla concentradora y difusor para estilizar el cabello según tus preferencias. Consigue un cabello suave, brillante y saludable con este secador de pelo de calidad profesional.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_797457-MLA49192142777_022022-O.webp",
                            Name = "Secador de Pelo Profesional Ionic Ceramic",
                            Price = 59299m
                        },
                        new
                        {
                            ProductId = new Guid("b54b08a5-a65a-4e2c-a46e-4ea604032066"),
                            CategoryId = 6,
                            Description = "Esta pelota de fútbol es perfecta para jugar con amigos o en familia. Su diseño clásico y su material resistente te brindarán horas de diversión.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_814346-MLU72542363030_112023-O.webp",
                            Name = "Pelota de fútbol",
                            Price = 29890m
                        },
                        new
                        {
                            ProductId = new Guid("4ce62fb7-d796-459e-8487-5ea3fcf96a50"),
                            CategoryId = 6,
                            Description = "Esta bicicleta de montaña es perfecta para los amantes del ciclismo. Su diseño resistente y duradero te permitirá disfrutar de tus aventuras al aire libre.",
                            Discount = 5,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_692292-MLA48659462745_122021-O.webp",
                            Name = "Bicicleta de montaña",
                            Price = 314689m
                        },
                        new
                        {
                            ProductId = new Guid("249db425-4a8c-4cc3-b4f6-746ad2057a27"),
                            CategoryId = 6,
                            Description = "Este juego de mesa es perfecto para pasar un rato divertido en familia. Su diseño atractivo y sus reglas sencillas te brindarán horas de entretenimiento.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_742516-MLA44728186422_012021-F.webp",
                            Name = "Juego de mesa para toda la familia",
                            Price = 19061m
                        },
                        new
                        {
                            ProductId = new Guid("1c099147-f374-4c71-a915-329269775478"),
                            CategoryId = 6,
                            Description = "Disfruta del agua con la tabla de paddle surf hinchable Aqua Marina Fusion. Fabricada con material de alta calidad, esta tabla ofrece estabilidad y durabilidad. Su diseño hinchable la hace fácil de transportar y almacenar. Equipada con una bomba de alta presión y una bolsa de transporte, es perfecta para explorar lagos, ríos y costas. ¡Sumérgete en la diversión con esta tabla de paddle surf!",
                            Discount = 8,
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0233/3953/2624/products/14-FUSION-01-2020-IMG_1737-2_1000x.jpg?v=1609160293",
                            Name = "Tabla de Paddle Surf Hinchable Aqua Marina Fusion",
                            Price = 189999m
                        },
                        new
                        {
                            ProductId = new Guid("2b0ef0a0-7afd-41ab-bed5-225744a7abd8"),
                            CategoryId = 7,
                            Description = "Estos bloques de construcción son perfectos para que los niños desarrollen su creatividad e imaginación. Con ellos podrán construir todo tipo de estructuras, desde casas y castillos hasta naves espaciales y robots.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_653633-MLU72122811116_102023-O.webp",
                            Name = "Bloques de construcción",
                            Price = 46509m
                        },
                        new
                        {
                            ProductId = new Guid("83d7e521-2116-41f8-9c53-0a8a2a1d8785"),
                            CategoryId = 7,
                            Description = "Esta muñeca es perfecta para que las niñas se diviertan y aprendan a cuidar de los demás. Viene con ropa y accesorios para que las niñas puedan crear todo tipo de historias.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_891562-MLU74194879919_012024-O.webp",
                            Name = "Muñeca",
                            Price = 27169m
                        },
                        new
                        {
                            ProductId = new Guid("7eb6003e-3c38-4ad4-a0be-e31766b46924"),
                            CategoryId = 7,
                            Description = "Este juego de mesa es perfecto para que los niños se diviertan en familia. Sus reglas sencillas y su diseño atractivo lo hacen ideal para niños de todas las edades.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_874287-MLU72637351761_112023-O.webp",
                            Name = "Juego de mesa para niños",
                            Price = 44399m
                        },
                        new
                        {
                            ProductId = new Guid("a337ae0a-5f04-48fa-89cc-0bc93fc42af8"),
                            CategoryId = 7,
                            Description = "Construye una de las maravillas del mundo con el set LEGO Creator Expert Taj Mahal. Este impresionante set incluye más de 9500 piezas para recrear fielmente este icónico monumento. Con detalles intrincados y una escala impresionante, esta maqueta proporciona una experiencia de construcción desafiante y gratificante para aficionados y coleccionistas. ¡Embárcate en un viaje arquitectónico con este magnífico set de LEGO!",
                            Discount = 9,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_794783-MLA54926679565_042023-O.webp",
                            Name = "l",
                            Price = 339999m
                        },
                        new
                        {
                            ProductId = new Guid("f0a370c5-86ee-46e2-b64e-92f405879a26"),
                            CategoryId = 8,
                            Description = "Estas manzanas frescas son de la mejor calidad y tienen un sabor delicioso. Son perfectas para comer como snack o para usar en recetas.",
                            Discount = 0,
                            ImageUrl = "https://img.freepik.com/foto-gratis/manzanas-rojas-frescas-suaves-jugosas-enteras-perfectas-escritorio-blanco_179666-271.jpg",
                            Name = "Manzanas frescas",
                            Price = 2999m
                        },
                        new
                        {
                            ProductId = new Guid("f62ad1ae-421e-4bcb-9f7d-06f389848b3e"),
                            CategoryId = 8,
                            Description = "Esta leche descremada es ideal para aquellos que buscan una opción más saludable. Es baja en calorías y grasa, pero aún así tiene un sabor delicioso.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_794418-MLU73783720994_012024-F.webp",
                            Name = "Leche descremada",
                            Price = 1790m
                        },
                        new
                        {
                            ProductId = new Guid("12b750b3-d860-4fb5-bae8-12c27cfac30f"),
                            CategoryId = 8,
                            Description = "Estas galletas de chocolate son perfectas para disfrutar con un café o un té. Son deliciosas y crujientes.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_770512-MLA52795200078_122022-O.webp",
                            Name = "Galletas de chocolate",
                            Price = 2849m
                        },
                        new
                        {
                            ProductId = new Guid("64f69e22-f82a-417d-b555-c2584d564afb"),
                            CategoryId = 8,
                            Description = "Explora el mundo del vino con este kit de degustación que incluye una selección de vinos de diferentes variedades y regiones. Cada botella está cuidadosamente seleccionada para ofrecer una experiencia única de degustación. Descubre nuevos sabores, aromas y texturas mientras disfrutas de una velada especial con amigos o familiares.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_2X_778460-MLA74696522802_022024-F.webp",
                            Name = "Kit de Degustación de Vinos",
                            Price = 4999m
                        },
                        new
                        {
                            ProductId = new Guid("78b2f450-068f-44ef-b27a-ba8e43ea0121"),
                            CategoryId = 9,
                            Description = "Este libro de ficción es una novela apasionante que te atrapará desde el principio.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_790538-MLU73106969282_122023-O.webp",
                            Name = "Libro de ficción",
                            Price = 22900m
                        },
                        new
                        {
                            ProductId = new Guid("2bbeec4c-d581-446b-9415-a3264b161830"),
                            CategoryId = 9,
                            Description = "Estos lápices de colores son ideales para que los niños exploren su creatividad.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_625215-MLU73129288734_122023-O.webp",
                            Name = "Lápices de colores",
                            Price = 19999m
                        },
                        new
                        {
                            ProductId = new Guid("90a2eff0-2b2b-45db-8b52-c9225f1eddfb"),
                            CategoryId = 9,
                            Description = "Este cuaderno de notas es perfecto para tomar apuntes en clase o en la oficina.",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_969804-MLU72605081373_102023-O.webp",
                            Name = "Cuaderno de notas",
                            Price = 11990m
                        },
                        new
                        {
                            ProductId = new Guid("15b1f0c3-ff75-4789-9194-26023aeab3c8"),
                            CategoryId = 9,
                            Description = "Descubre una variedad de deliciosas recetas de diferentes culturas y regiones del mundo con este libro de cocina. Desde platos tradicionales hasta opciones modernas, este libro te guiará a través de pasos sencillos para crear comidas increíbles en tu propia cocina. Con fotografías inspiradoras y consejos útiles, es perfecto para chefs aficionados y entusiastas de la cocina.",
                            Discount = 8,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_622837-MLU74371917389_022024-O.webp",
                            Name = "Libro de Cocina: Recetas del Mundo",
                            Price = 1999m
                        },
                        new
                        {
                            ProductId = new Guid("b592caeb-06a5-4749-b4a8-456376e67c2e"),
                            CategoryId = 10,
                            Description = "Estas tijeras de podar son ideales para cortar ramas y tallos de plantas.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_997006-MLU73673556155_122023-O.webp",
                            Name = "Tijeras de podar",
                            Price = 64368m
                        },
                        new
                        {
                            ProductId = new Guid("9aa22ce1-c775-4c0f-8492-7d4f7c660c2a"),
                            CategoryId = 10,
                            Description = "Esta manguera de jardín es perfecta para regar tus plantas y flores.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_924765-MLU75436466640_042024-O.webp",
                            Name = "Manguera de jardín",
                            Price = 41582m
                        },
                        new
                        {
                            ProductId = new Guid("4ac4a634-f001-4516-8be9-d5e53ec0eb4c"),
                            CategoryId = 10,
                            Description = "Este kit de herramientas básicas es perfecto para realizar pequeños trabajos de bricolaje en casa.",
                            Discount = 10,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_649163-MLU75509398453_032024-O.webp",
                            Name = "Kit de herramientas básicas",
                            Price = 65499m
                        },
                        new
                        {
                            ProductId = new Guid("2d0a0e42-2d3e-4a35-8923-e4ce87fbd2b0"),
                            CategoryId = 10,
                            Description = "Haz que tu jardín florezca con este completo kit de herramientas de jardinería. Incluye una variedad de herramientas esenciales como palas, rastrillos, tijeras de podar y más, todo en un práctico estuche. Diseñadas para durar y facilitar el trabajo en el jardín, estas herramientas te ayudarán a mantener tu espacio verde hermoso y saludable durante todo el año.",
                            Discount = 9,
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_845110-MLA43219745617_082020-O.webp",
                            Name = "Kit de Herramientas de Jardinería",
                            Price = 2299m
                        });
                });

            modelBuilder.Entity("Domain.Entitys.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entitys.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Product");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("Sale");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entitys.Product", b =>
                {
                    b.HasOne("Domain.Entitys.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entitys.SaleProduct", b =>
                {
                    b.HasOne("Domain.Entitys.Product", "Product")
                        .WithMany("SaleProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitys.Sale", "Sales")
                        .WithMany("SaleProducts")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Domain.Entitys.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entitys.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Domain.Entitys.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
